# 1. Create a 3x3x3 array with random values 

In [1]:
#method 1

import numpy as np
a=np.array([[[1,2,3],[2,3,4],[1,3,4]],[[2,3,4],[5,7,6],[3,7,8]],[[5,8,9],[2,6,4],[2,7,3]]])
print(a)
print("\n Type of a is")
print(type(a))
print("\n shape of a is")
print(a.shape)

[[[1 2 3]
  [2 3 4]
  [1 3 4]]

 [[2 3 4]
  [5 7 6]
  [3 7 8]]

 [[5 8 9]
  [2 6 4]
  [2 7 3]]]

 Type of a is
<class 'numpy.ndarray'>

 shape of a is
(3, 3, 3)


In [10]:
#method 2

np.random.random((3,3,3))

array([[[0.43086153, 0.68402537, 0.41471171],
        [0.17573344, 0.95783677, 0.74858361],
        [0.41852138, 0.32736936, 0.60356165]],

       [[0.66719324, 0.92659102, 0.55035532],
        [0.30574002, 0.444636  , 0.44761093],
        [0.18231764, 0.17007034, 0.21183014]],

       [[0.05585473, 0.31006541, 0.90371559],
        [0.93548266, 0.07468611, 0.47002137],
        [0.31587646, 0.7018306 , 0.58855784]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [14]:
a1=np.eye(5,5)
a1[1][0] +=1
a1[2][1] +=2
a1[3][2] +=3
a1[4][3] +=4
print(a1)

[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [0. 2. 1. 0. 0.]
 [0. 0. 3. 1. 0.]
 [0. 0. 0. 4. 1.]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [16]:
a2=np.zeros((8,8))
for i in range(8):
    for j in range(8):
        if(i+j)%2==0:
            a2[i][j]=1
print(a2)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


# 4. Normalize a 5x5 random matrix

In [25]:
a3=np.random.random((5,5))
print("\n Original Array")
print("\n",a3)
max=a3.max()
min=a3.min()
a3=(a3-min)/(max-min)
print("\n After Normalization")
print("\n",a3)


 Original Array

 [[0.41644344 0.95664518 0.7358861  0.90777801 0.2888118 ]
 [0.96674289 0.41167143 0.1178943  0.74728624 0.62951313]
 [0.57426772 0.42390636 0.55417618 0.19316228 0.67413645]
 [0.20216913 0.00165967 0.46273045 0.98585186 0.54885582]
 [0.20825824 0.87108994 0.15182381 0.12796957 0.74142698]]

 After Normalization

 [[0.4214459  0.97032421 0.74601936 0.92067215 0.29176428]
 [0.9805841  0.41659725 0.11810155 0.7576026  0.63793786]
 [0.58180511 0.42902869 0.56139087 0.19457847 0.68327791]
 [0.20372998 0.         0.46847636 1.         0.55598505]
 [0.2099169  0.8833948  0.15257603 0.12833865 0.75164924]]


# 5.  How to find common values between two arrays?

In [27]:
a5=np.array([1,2,3,4])
print("First Array",a5)
a6=np.array([2,4,5,6])
print("\n Second Array",a6)
print("\n Common values between two Arrays:")
print("\n",np.intersect1d(a5,a6))


First Array [1 2 3 4]

 Second Array [2 4 5 6]

 Common values between two Arrays:

 [2 4]


# 6.How to get the dates of yesterday, today and tomorrow?

In [29]:
Yesterday=np.datetime64('today')-np.timedelta64(1)
print("yesterday's date is",Yesterday)
today =np.datetime64('today')
print("\n Today's date is ",today)
Tomorrow=np.datetime64('today')+np.timedelta64(1)
print("\n Tomorrow's date is",Tomorrow)

yesterday's date is 2020-07-25

 Today's date is  2020-07-26

 Tomorrow's date is 2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [30]:
a7=np.random.random((2,2))
a8=np.random.random((2,2))
print((a7==a8).all())     # To check Matrix wise
print((a7==a8))           # To check Element Wise


False
[[False False]
 [False False]]


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [34]:
#method 1

a9=np.random.random(10)
print("\n Original Vector\n",a9)
max=a9.max()
print("\n Max value ",max)
for i in range(len(a9)):
    if(a9[i]==max):
        a9[i]=0
print("\n After Replacement")
print("\n",a9)


 Original Vector
 [0.84510979 0.15164213 0.97778043 0.51468545 0.49120222 0.51919307
 0.06763384 0.00409304 0.60931188 0.69328636]

 Max value  0.9777804278764572

 After Replacement

 [0.84510979 0.15164213 0.         0.51468545 0.49120222 0.51919307
 0.06763384 0.00409304 0.60931188 0.69328636]


In [36]:
# method 2

a9=np.random.random(10)
print("\n Original Vector\n",a9)
a9[a9.argmax()]=0
print("\n After Replacement")
print(a9)


 Original Vector
 [0.73569769 0.29166479 0.33685352 0.45847852 0.90399523 0.12102614
 0.84225845 0.80425461 0.3421082  0.61179218]

 After Replacement
[0.73569769 0.29166479 0.33685352 0.45847852 0.         0.12102614
 0.84225845 0.80425461 0.3421082  0.61179218]


# 9. How to print all the values of an array?

In [9]:
a10=np.array([[[1,2,3],[2,3,4],[1,3,4]],[[2,3,4],[5,7,6],[3,7,8]]])
for i in range(a10.shape[0]):
    for j in range(a10.shape[1]):
        print(a10[i][j])

[1 2 3]
[2 3 4]
[1 3 4]
[2 3 4]
[5 7 6]
[3 7 8]


# 10.Subtract the mean of each row of a matrix

In [2]:
s=np.array([[1,2,3,4],[5,6,7,8],[1,3,4,5]])
print("before subtraction:")
print(s)
t=s-s.mean(axis=1,keepdims=True)
print("after subtraction:")
print(t)

before subtraction:
[[1 2 3 4]
 [5 6 7 8]
 [1 3 4 5]]
after subtraction:
[[-1.5  -0.5   0.5   1.5 ]
 [-1.5  -0.5   0.5   1.5 ]
 [-2.25 -0.25  0.75  1.75]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [3]:
b=np.array([1,2,3,4,5,6,7,8])
b[2:]+=1
print(b)

[1 2 4 5 6 7 8 9]


# 12.How to get the diagonal of a dot product?

In [4]:
c=np.array([[1,2],[3,4]])
d=np.array([[5,6],[7,8]])
e=np.diagonal(c.dot(d))
print(e)

[19 50]


# 13.How to find the most frequent value in an array?

In [5]:
f=np.array([1,2,1,4,1,5,1,6])
print(f)
print("most frequent value in the array:")
print(np.bincount(f).argmax())

[1 2 1 4 1 5 1 6]
most frequent value in the array:
1


# 14.How to get the n largest values of an array

In [7]:
w=np.array([1,2,3,4,5,6,7,8])
print(w)
n=1
print(w[np.argsort(w)[-n:]])


[1 2 3 4 5 6 7 8]
[8]


# 15.How to create a record array from a regular array?

In [9]:
a1=np.array([10,20,30,40])
a2=np.array(['Orange','Grape','Banana','Apple'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3])
print(result)

[(10, 'Orange', 12.2) (20, 'Grape', 15. ) (30, 'Banana', 20. )
 (40, 'Apple', 40. )]
